spring:
  application:
    name: gv4-scheduler

#  datasource:
#    url:
#    username:
#    password:
#    name:

  mail:
    host: smtp.gmail.com
    port: 587
    username: gv4.scheduler@gmail.com
    password: pvekflwfzetnpmzm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    defaultsRecipients:
      - mikolaj.mialkowski@outlook.com

source:
  github:
    gv3:
      raw: https://raw.githubusercontent.com/bibixx/zdaj-se-pjatk-data/master
      apbd: /apbd.json