spring:
  application:
    name: gv4-scheduler

#  datasource:
#    url:
#    username:
#    password:
#    name:

  mail:
    host: smtp.gmail.com
    port: 587
    username: project.entropy.dev
    password: 254c7394-8397-11ec-a8a3-0242ac120002
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    defaultsRecipients:
      - mikolaj.mialkowski@outlook.com